<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ajaxjs</groupId>
        <artifactId>ajaxjs-cms</artifactId>
        <version>1.0.6</version>
        <relativePath/>
    </parent>

    <artifactId>base</artifactId>
    <name>aj-spring</name>
    <version>1.4</version>
    <packaging>jar</packaging>
    <description>Minimal requirements for the component of Spring Framework</description>
    <url>https://aj-docs.ajaxjs.com/</url>

    <scm>
        <url>https://github.com/lightweight-component/aj-framework/tree/master/aj-spring</url>
        <connection>scm:git:https://github.com/lightweight-component/aj-framework.git</connection>
    </scm>

    <issueManagement>
        <system>Github Issues</system>
        <url>https://github.com/lightweight-component/aj-framework/issues</url>
    </issueManagement>

    <dependencies>
        <!--  Spring  -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <scope>provided</scope>
        </dependency>

        <!--  Spring 测试  -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <!-- Tomcat DB POOL -->
        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-jdbc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.ajaxjs</groupId>
            <artifactId>sqlman</artifactId>
            <version>2.2</version>

            <exclusions>
                <!-- 排除 Jackson 核心数据绑定库 -->
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
                <!-- 排除 Jackson 核心解析库 -->
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.junit.jupiter</groupId>
                    <artifactId>junit-jupiter</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>jakarta.servlet</groupId>
                    <artifactId>jakarta.servlet-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>