server:
  port: 8081

spring:
  #  main:
  #    lazy-initialization: true
  #  autoconfigure:
  #    exclude:
  #      - org.redisson.spring.starter.RedissonAutoConfigurationV2 # 禁用 Redis
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: creative-martin-46984.upstash.io
    port: 6379
    password: AbeIAAIjcDFmZmVmY2M2YzViYmQ0M2U3YWJmODU3NGNlYzNhMTNkMHAxMA
    ssl: true

dubbo:
  application:
    logger: slf4j
    name: DemoApplication
  protocol:
    name: tri
    port: 50051

api:
  EncryptedBody:
    privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIwEbyJboyyef3848da7iWrdkVGPhc/m5N/dkEQtEv5EwzOhif06vhcX7S/X7EbWHLzGglkEXvzYcLGPPY6m9eVw0JRudXccd4M/HWOvwBhukSEx5gjftGTtDMh/WCS1zmlaqicyyB2Hy1EXwVdY6zT+gzMnN92oVeD6HERqDN7PAgMBAAECgYB+t8Sco7KZvxhEW5UDcdZ8EOpjljDUZ3Lb5/mYufJmjHTdVWU8+NzwqYbPterwcPaxIjb1uS7+RiQ3jht370K6daZwuii7ipuS8KbghnJodlE6oY4FthFo5l2BJbdnIL7ahiMK2fWN9fj4I4r+7yaenn8Vyq1y94hVoEblJcweAQJBAOkxO86p0/DJ4KdyPVjjz0gtzc5YZSqUjuvKydgblJ7YW6oKiYcqAmnIBQ/Q1oky7ttQ0BvfzET+QxgnZs0CyDECQQCZtj8AOrpcIGvGuV7o6Bl2PzQ7QTq4i+rCCqV8G22p0qWY4Lvcpby7yB86IamDHCRqMuu88taZBWFZpmRKt1b/AkEAnWKlQu5MJQ+bmGf6D6xxkf2YEdSHMx3g+DN912WGAU91TmaeO6OWzV46TFpe8Wp2237HdoitjUMudXbiYyulgQJAV+A71kq83gxe8UZqvyZp4BM0LigVhQnglTx27SPVJwBZUbQxUmyiIIzBZX93JJCDNP+Vi/kcvHC5/gHFVn3ISwJAbMK933DY4CW+dLWdu5DdkVz3FUeHLg7OmCIYAVqQ89eMrkmXzhR9fqMYF7J6BpwukrB0rGY1EooRdPwQ40/tqg==

management:
  endpoints:
    web:
      exposure:
        include: "*"


#        host: smtp.163.com
#        protocol: smtp
#        username: antsitya@163.com
#        password: ant163authcode