INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'article', 'sys_article', 1, 1, 0, 1, NULL, '{"joinTableName": "sys_datadict", "mainTableJoinColumn": "catelog_id", "joinedTableJoinColumn": "id", "fieldsToSelectFromJoinedTable": ["name AS catelogName"]}', 0, NULL, NULL, '2025-11-17 12:22:52', NULL, NULL, '2026-01-31 00:01:42');

--- shop
INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'spu', 'shop_spu', 1, 0, 0, 1, NULL, NULL, 0, NULL, NULL, '2026-02-24 23:09:46', NULL, NULL, '2026-02-24 23:09:46');
INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'sku', 'shop_sku', 1, 0, 0, 1, NULL, NULL, 0, NULL, NULL, '2026-02-24 23:10:27', NULL, NULL, '2026-02-24 23:10:27');
INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'attrib_def', 'shop_attribute_definition', 1, 0, 0, 1, NULL, NULL, 0, NULL, NULL, '2026-02-24 23:49:16', NULL, NULL, '2026-02-24 23:49:16');
INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'attrib_value', 'shop_attribute_value', 1, 0, 0, 1, NULL, NULL, 0, NULL, NULL, '2026-02-24 23:49:47', NULL, NULL, '2026-02-25 11:10:47');
INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'sku_attrib_value', 'shop_sku_attribute_value', 1, 0, 0, 1, NULL, NULL, 0, NULL, NULL, '2026-02-24 23:50:21', NULL, NULL, '2026-02-24 23:50:37');
INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'order', 'shop_order', 1, 0, 0, 1, NULL, NULL, 0, NULL, NULL, '2026-02-25 00:10:06', NULL, NULL, '2026-02-25 00:10:06');
INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'order_invoice', 'shop_order_invoice', 1, 0, 0, 1, NULL, NULL, 0, NULL, NULL, '2026-02-25 00:11:57', NULL, NULL, '2026-02-25 00:11:57');
INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'refund_record', 'shop_refund_record', 1, 0, 0, 1, NULL, NULL, 0, NULL, NULL, '2026-02-25 00:12:37', NULL, NULL, '2026-02-25 00:12:37');
INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'pay_channel', 'shop_pay_channel', 1, 0, 0, 1, NULL, NULL, 0, NULL, NULL, '2026-02-25 00:13:37', NULL, NULL, '2026-02-25 00:13:37');
INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'address', 'shop_address', 1, 0, 1, 1, 7, NULL, 0, NULL, NULL, '2026-01-31 15:28:42', NULL, NULL, '2026-02-25 11:09:39');
INSERT INTO `ds_namespace` ( `namespace`, `table_name`, `list_order_by_date`, `tenant_isolation`, `current_user_only`, `filter_deleted`, `save_user_on_create`, `table_join`, `stat`, `creator`, `creator_id`, `create_date`, `updater`, `updater_id`, `update_date`) VALUES ( 'transaction', 'shop_payment_transaction', 1, 0, 0, 1, NULL, NULL, 0, NULL, NULL, '2026-02-10 11:10:23', NULL, NULL, '2026-02-10 11:10:23');
