server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: springboot-hot-cpu
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        cachecontrol:
          max-age: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.hotcpu: INFO
    org.springframework: WARN
    org.apache: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"